$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$sourceDir = Join-Path $repoRoot 'agent-rules'
$ruleNames = @('coding', 'git', 'python', 'worktree')
$header = '<!-- Generated by scripts/render-agent-rules; edit agent-rules/ instead. -->'

foreach ($rule in $ruleNames) {
    if (-not (Test-Path (Join-Path $sourceDir "$rule.md"))) {
        throw "Missing agent rule: $rule.md"
    }
}

function Write-CombinedRules([string]$destination, [string]$title) {
    $directory = Split-Path -Parent $destination
    New-Item -ItemType Directory -Force -Path $directory | Out-Null
    $content = @($header, "# $title")
    foreach ($rule in $ruleNames) {
        $content += ''
        $content += (Get-Content -Raw (Join-Path $sourceDir "$rule.md"))
    }
    Set-Content -Encoding utf8 -Path $destination -Value $content
}

$claudeRulesDir = Join-Path $repoRoot '.claude\rules'
New-Item -ItemType Directory -Force -Path $claudeRulesDir | Out-Null
foreach ($rule in $ruleNames) {
    $content = @($header, '', (Get-Content -Raw (Join-Path $sourceDir "$rule.md")))
    Set-Content -Encoding utf8 -Path (Join-Path $claudeRulesDir "$rule.md") -Value $content
}

Write-CombinedRules (Join-Path $repoRoot '.codex\AGENTS.md') 'Global agent guidance'
Write-CombinedRules (Join-Path $repoRoot '.agent-rules\copilot.instructions.md') 'Global agent guidance'
